db_file: "bot.db"

bot_url: "https://t.me/VkPostFinderBot"

messages:
  responses:
    start: "Привет! Чтобы сохранять ссылки в своем Pocket аккаунте, для начала вам необходимо дать мне на это доступ. Для этого переходите по ссылке:\n%s"
    already_authorized: "Вы уже авторизовались с помощью своего Pocket аккаунта. Присылайте ссылку чтобы сохранить"
    unknown_command: "Такой команды не существует"
    link_saved: "Ссылка успешно сохранена!"
  errors:
    default: "Произошла неизвестная ошибка"
    invalid_url:  "Это ссылка невалидна"
    unauthorized: "Вы не авторизированны"
    unable_to_save: "Не удалось сохранить ссылку в Pocket. Попробуйте ещё раз"
